apiVersion: v1
kind: Service
metadata:
  name: {{ include "sim.fullname" . }}-nginx
  labels:
    {{- include "sim.componentLabels" (dict "ctx" . "component" "nginx") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sim.componentSelector" (dict "ctx" . "component" "nginx") | nindent 4 }}
