{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sim.fullname" $ }}-{{ $name }}
  labels:
    {{- include "sim.componentLabels" (dict "ctx" $ "component" $name) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sim.componentSelector" (dict "ctx" $ "component" $name) | nindent 4 }}
{{- end }}
