# ============================================================
# helm template 로컬 테스트용
# helm template test ../../eks-simulator-helm -f values-kia-user-b.yaml
# ============================================================
userId: "user-b"
oemId: "kia"
imageRegistry: "123456789012.dkr.ecr.ap-northeast-2.amazonaws.com"

ingress:
  baseDomain: "sim.example.com"
  certArn: "arn:aws:acm:ap-northeast-2:123456789012:certificate/aaaa-bbbb-cccc"

hybridNode:
  enabled: true

services:
  simulator-can:
    image:
      tag: "v1.4.0"
  simulator-server:
    image:
      tag: "v1.5.0"
  simulator-vehicle:
    image:
      tag: "v1.2.0"
  target-android:
    image:
      tag: "v2.1.0"
    resources:
      requests: { cpu: 1000m, memory: 2Gi }
      limits:   { cpu: 4000m, memory: 4Gi }
  target-cluster:
    image:
      tag: "v1.1.0"
